### ISSUE TITLE
Research icon size

### ISSUE THREAD

**Issue by 0n0w1c** [davidrios/MiniRoboports#1]
The icon size should be adjusted, it does not display correctly when viewing the Research. I tested, and the following change displays the icon correctly:

technologies.lua

-- icon_size = 128,
++ icon_size = 256,

**Comment by davidrios** [comment]
Fixed. Thanks, mate!

**Comment by 0n0w1c** [comment]
Very helpful mod, much appreciated. And thank you for the fix.
